#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs terraform tests found in the specified directory or the current
# directory if not specified.

# The script also accepts --preserve_providers or --P which will NOT
# remove the .terraform folder generated by terraform init. This is useful
# as it speeds up the test time for iterating while writing the tests.

#######################################
# Prints an error message and exits 1. Helper function for making it clearer
# where a failure occurs in test logs. (use with `|| fail "reason"`)
# Arguments:
#   message - one or more strings to echo
#######################################
fail() {
  echo -e "\n\n[SCP_ERROR_LOG]: Failure: ${@}\n\n"
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dir_to_test=*)
      dir_to_test="${1#*=}"
      ;;
    --preserve_providers)
      preserve_providers=true
      ;;
    --P)
      preserve_providers=true
      ;;
    *)
      printf "***************************\n"
      printf "* Error: Invalid argument.*\n"
      printf "***************************\n"
      exit 1
  esac
  shift
done

if [[ ! -v dir_to_test ]]; then
  # If no directory is specified, use the current directory.
  dir_to_test='.'
fi

if [[ ! -v preserve_providers ]]; then
  preserve_providers=false
fi

TF_BIN="${TF_BIN:-terraform}"

set -x

testfiles=($(find "$dir_to_test" -name '*.tftest.hcl' -not -path './tools/tftesting/*'))

testdirs=()
for file in "${testfiles[@]}"; do
  testdirs+=($(dirname "$file"))
done

# The above may find the same directory multiple times, one for each
# test file in the directory. We dedup them here.
testdirs=($(echo ${testdirs[@]} | sort | tr ' ' '\n' | uniq))

$TF_BIN --version

for dir in "${testdirs[@]}"; do
  $TF_BIN -chdir="$dir" init || fail "TF init failed in $dir"
  $TF_BIN -chdir="$dir" test || fail "TF test failed in $dir"
  if [[ "$preserve_providers" == false ]]; then
    rm -rf "$dir/.terraform"
  fi
done