# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Transform: AWS::Serverless-2016-10-31
Description: KeyGenerationLambda
Resources:

  Consume:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.google.scp.coordinator.keymanagement.keygeneration.app.aws.KeyGenerationLambda
      CodeUri: {lambda_location}
      Runtime: java11
      MemorySize: 1024
      Timeout: 100
      Environment:
        Variables:
          KEYSTORE_TABLE_NAME: ""
          KEYSTORE_ENDPOINT_OVERRIDE: ""
          ENCRYPTION_KEY_ARN: ""
          KEYSTORE_TABLE_REGION: ""
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          KMS_ENDPOINT_OVERRIDE: ""
          KEY_GENERATION_KEY_COUNT: ""
          KEY_GENERATION_VALIDITY_IN_DAYS: ""
          KEY_GENERATION_TTL_IN_DAYS: ""
